    steps:
    # build the container image
    - name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE', '.']
    # push the container image to Container Registry
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE']
    # Deploy container image to Cloud Run
    - name: 'gcr.io/cloud-builders/gcloud'
      args: ['alpha', 'run', 'deploy', '$_SERVICE', '--image', 'gcr.io/$PROJECT_ID/$_SERVICE', '--region', '${_REGION}']
    images: ['gcr.io/$PROJECT_ID/$_SERVICE']
    substitutions:
    _SERVICE: hello-web # service name
    _REGION: us-central1 # region